# Este archivo configura el analizador de Dart para revisar errores, advertencias y buenas prácticas.

# Reglas recomendadas para proyectos Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    # Puedes personalizar o extender estas reglas si lo deseas
    # prefer_single_quotes: true
    # avoid_print: false

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    lines-of-code: 100
    maximum-nesting-level: 5

  rules:
    - prefer-trailing-comma
    - avoid-non-null-assertion
    - no-equal-then-else
    - avoid-unnecessary-conditionals
    - member-ordering
