name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2" # Usa tu versión o déjalo así

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart Code Metrics
        run: flutter pub run dart_code_metrics:metrics lib > report.json

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=panapan
            -Dsonar.organization=wilmer-hernandez-herrera
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=lib
            -Dsonar.dart.dcm.reportPaths=report.json
